-- Ejecutar en BigQuery Console → proyecto portfolio-app-9a4bc
-- Dataset: facturas_dataset

CREATE TABLE IF NOT EXISTS `portfolio-app-9a4bc.facturas_dataset.cubo_ventas` (
  fecha_emision        STRING,
  documento            STRING,
  tipo_venta           STRING,
  termino_pago_resumen STRING,
  documento_id         STRING,
  moneda               STRING,
  tipo_cambio          FLOAT64,
  precio               FLOAT64,
  almacen              STRING,
  anio                 INT64,
  mes_texto            STRING,
  dia_num              INT64,
  numero_legal         STRING,
  fecha_vencimiento    STRING,
  dias_vencimiento     INT64,
  fise                 STRING,
  precio_antes_dscto   FLOAT64,
  sucursal             STRING,
  producto_id          STRING,
  unidad_medida        STRING,
  producto             STRING,
  categoria            STRING,
  familia              STRING,
  sub_familia          STRING,
  linea                STRING,
  marca                STRING,
  grupo_producto       STRING,
  cliente_id           STRING,
  cliente              STRING,
  zona_id              STRING,
  zona                 STRING,
  cliente_categoria    STRING,
  distrito             STRING,
  provincia            STRING,
  departamento         STRING,
  pais                 STRING,
  vendedor             STRING,
  analista             STRING,
  supervisor           STRING,
  gerencia             STRING,
  unidad_negocio       STRING,
  grupo_unidad_negocio STRING,
  tipo_gerencia        STRING,
  procedencia          STRING,
  total_con_impuesto   FLOAT64,
  galones              FLOAT64,
  total_costo          FLOAT64,
  total_sin_impuesto   FLOAT64,
  cantidad             FLOAT64,
  descuento            FLOAT64,
  descuento_financiero FLOAT64,
  descuento_porc       FLOAT64,
  otros_descuentos     FLOAT64,
  barriles             FLOAT64,
  created_at           TIMESTAMP
);

